global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'market-scanner'
    static_configs:
      - targets: ['host.docker.internal:8000']  # For Docker on Mac/Windows
        # Use 'localhost:8000' if running directly on Linux

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']